#ifndef _R2BOT_XBOX360CONTROLLER_CONFIG
#define _R2BOT_XBOX360CONTROLLER_CONFIG

#define _WINSOCK_DEPRECATED_NO_WARNINGS

#undef  DEBUG_PRINTS

#define DEVICE_NAME "XBOX360CONTROLLER"
#undef  USE_KINECT1
#undef  USE_KINECT2
#undef  USE_MOTORS
#undef  USE_ULTRASONIC
#undef  USE_R2SERVER

#endif