#ifndef _R2BOT_CONFIG
#define _R2BOT_CONFIG

#define _WINSOCK_DEPRECATED_NO_WARNINGS

#define DEBUG_PRINTS

#define DEVICE_NAME "NUC"
#undef  USE_KINECT1
#undef  USE_KINECT2
#undef  USE_MOTORS
#undef  USE_ULTRASONIC
#define USE_R2SERVER

#endif